---
- name: Checking the api_interface is present
  fail: "msg='Please check the api_interface property - interface {{ api_interface }} not found'"
  when:
    - inventory_hostname not in groups['deployment']
    - api_interface not in ansible_interfaces

- name: Checking the api_interface is active
  fail: "msg='Please check the api_interface settings - interface {{ api_interface }} is not active'"
  when:
    - inventory_hostname not in groups['deployment']
    - hostvars[inventory_hostname]['ansible_' + api_interface]['active'] != True

- name: Checking the api_interface configuration
  fail: "msg='Please check the api_interface settings - interface {{ api_interface }} configuration missing'"
  when:
    - inventory_hostname not in groups['deployment']
    - hostvars[inventory_hostname]['ansible_' + api_interface]['ipv4'] is not defined

- name: Checking the api_interface ip address configuration
  fail: "msg='Please check the api_interface settings - interface {{ api_interface }} ip address problem'"
  when:
    - inventory_hostname not in groups['deployment']
    - api_interface_address is not defined
